<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "schema_injector"
 *
 * Auto generated by Extension Builder 2016-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Schema.org Injector',
	'description' => 'This extension will inject schema.org annoations into your rendered web page.',
	'category' => 'plugin',
	'author' => 'Stefan Haberl, Mahtias Meinschad',
	'author_email' => 'stefan.haberl@student.uibk.ac.at, mathias.meinschad@student.uibk.ac.at',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '7.6.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.5.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);